### ISSUE TITLE
"Issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by yuu-developer** [yuu-developer/TypeLearnEnglish#14]
##概要
MVPリリースでは、ユーザー登録、ログイン、プロフィール管理、英文タイピング練習、英文解説表示、およびタイピングスコアの計測と表示という主要機能を提供します。
ユーザー登録機能は、新規ユーザーがアプリにアカウントを登録できる機能。ユーザーはユーザー名、メールアドレス、パスワードを入力。
ログイン機能は、既存のユーザーがメールアドレスとパスワードを使用してアプリにログインできる機能。
プロフィール機能はユーザーが自己紹介文やアイコン画像など、個人のプロフィール情報を編集できる機能。
英文タイピング機能は、ユーザーが様々な英文をタイピングして学習することができる機能。
英文解説機能は、英文に関する詳細な解説を提供する機能。文法、単語の意味、使用例が含まれる。
スコア計測と表示機能は、ユーザーのタイピングテストの結果を計測し、スコアとして表示する機能。

##実装予定の機能
- [ ] ユーザー登録機能
- [ ] ログイン機能
- [ ]  プロフィール機能
- [ ] 英文タイピング機能
- [ ] スコア計測と表示機能
- [ ] 英文解説機能

##必要なページ
- [ ] トップページ(未ログイン)
- [ ] 登録フォームページ
- [ ] ログインフォームページ
- [ ] トップページ
- [ ] マイページ
- [ ] プロフィール編集ページ
- [ ] タイピング練習ページ
- [ ] スコア表示ページ
- [ ] 英文一覧ページ
- [ ] 英文解説ページ

**Comment by tarakish** [comment]
Projectsにアクセスしましたが、カンバン・issue・ストーリーポイントが確認できませんでした。
カリキュラムをご確認の上、上記が確認できる状態でご提出をお願いいたします。
![スクリーンショット 2024-05-02 20 03 46](https://github.com/yuu-developer/TypeLearnEnglish/assets/71510236/686c93c9-b426-4834-8339-7b4b65d48210)

**Comment by yuu-developer** [comment]
ご返信ありがとうございます。大変失礼しました。
ご確認いただけるよう修正しました、よろしくお願いいたします。

**Comment by tmtkzk0823** [comment]
ご対応ありがとうございます。
以下追加のコメントです。

---

- デプロイ、rails newなどのカードも作成しましょう。

- 外部APIや技術に関して調査するものがあれば、それもカードを用意しましょう。

また、ストーリーポイント5を付けているカードですが、初めて取り組むものや見通しが立っていないものにポイント5を付けているように見受けられました。ストーリーポイント1,2になるまで細分化することで、分かっている箇所、不透明な箇所が可視化されますし、進捗を感じながら開発を進めることができます。

**Comment by yuu-developer** [comment]
ご指導ありがとうございます。ご指摘頂いたタスクを分解しました。
また、MVPリリース時点では外部APIは使用しない方向で考えてます。
ご確認のほど、よろしくお願いいたします。

**Comment by Tsuchiya2** [comment]
概ね良いかと思います。LGTMです。

---

■MVP時ではなく本リリース時で良いと思ったもの
・マイページ作成
・プロフィールの更新
・プロフィールアイコン実装

**Comment by yuu-developer** [comment]
ありがうございます。
ご指導いただきました３点の機能は本リリース時に変更させて頂きます。

**Comment by yuu-developer** [comment]
更新後
##概要
MVPリリースでは、ユーザー登録、ログイン、プロフィール管理、英文タイピング練習、英文解説表示、およびタイピングスコアの計測と表示という主要機能を提供します。
ユーザー登録機能は、新規ユーザーがアプリにアカウントを登録できる機能。ユーザーはユーザー名、メールアドレス、パスワードを入力。
ログイン機能は、既存のユーザーがメールアドレスとパスワードを使用してアプリにログインできる機能。
英文タイピング機能は、ユーザーが様々な英文をタイピングして学習することができる機能。
英文解説機能は、英文に関する詳細な解説を提供する機能。文法、単語の意味、使用例が含まれる。
スコア計測と表示機能は、ユーザーのタイピングテストの結果を計測し、スコアとして表示する機能。

##実装予定の機能
- [ ] ユーザー登録機能
- [ ] ログイン機能
- [ ] 英文タイピング機能
- [ ] スコア計測と表示機能
- [ ] 英文解説機能

##必要なページ
- [ ] トップページ(未ログイン)
- [ ] 登録フォームページ
- [ ] ログインフォームページ
- [ ] トップページ
- [ ] タイピング練習ページ
- [ ] スコア表示ページ
- [ ] 英文一覧ページ
- [ ] 英文解説ページ
