### ISSUE TITLE
MVPリリース　レビュー依頼

### ISSUE THREAD

**Issue by yuu-developer** [yuu-developer/TypeLearnEnglish#54]
大変お世話になっております。
お忙しいところ恐れ入りますが、ご確認のほどよろしくお願い致します。

## 各種情報
サービス名：TypeLearnEnglish
サービスURL：https://typelearnenglish-1.onrender.com

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [x] ユーザー登録機能
- [x] ログイン機能
- [x] 英文タイピング機能
- [x] スコア計測と表示機能
- [x] 英文解説機能

## 必要なページ
- [x] トップページ(未ログイン)
- [x] 登録フォームページ
- [x] ログインフォームページ
- [x] トップページ
- [x] タイピング練習ページ
- [x] スコア表示ページ
- [x] 英文一覧ページ
- [x] 英文解説ページ

## READMEレビュー時から変更した機能
以下の機能は本リリースに変更しました。
- [ ] マイページ作成
- [ ] プロフィールの更新
- [ ] プロフィールアイコン実装
また、細かいレイアウト調整などもMVPリリースでは行なっておりません。

## 本リリース時に実装したい機能
- [ ] 辞書機能
- [ ] パスワードリセット機能
- [ ] 進捗ダッシュボード機能
- [ ] プロフィール機能
- [ ] ゲストログイン機能
- [ ] スコア共有機能
- [ ] マルチプレイヤーモード
- [ ] 利用規約ページ
- [ ] プライバシーポリシーページ
- [ ] お問い合わせページ

## サービスイメージがわかるようなスクリーンショット等
管理画面など通常ユーザーが触れない機能はございません。

## トップページ（未ログイン）：
[![Image from Gyazo](https://i.gyazo.com/f852c3df6bfdad5560852008bbff9c34.jpg)](https://gyazo.com/f852c3df6bfdad5560852008bbff9c34)

## トップページ（ログイン後）：
[![Image from Gyazo](https://i.gyazo.com/a886caaa7e9d51c022e9022f23fe0e91.jpg)](https://gyazo.com/a886caaa7e9d51c022e9022f23fe0e91)

## タイピング練習ページ（難易度選択画面）：クリックして難易度選択します
[![Image from Gyazo](https://i.gyazo.com/2961a75a85ea8d25f406419b580a0740.png)](https://gyazo.com/2961a75a85ea8d25f406419b580a0740)

## タイピング練習ページ：スタートボタンで5秒のカウントダウン後開始されます。
[![Image from Gyazo](https://i.gyazo.com/6f29fc4ebbf6f0c901632667138f156b.png)](https://gyazo.com/6f29fc4ebbf6f0c901632667138f156b)

## スコア表示ページ：スコアと難易度が表示されます
[![Image from Gyazo](https://i.gyazo.com/ed092218af59bec5aee0728d67111d24.png)](https://gyazo.com/ed092218af59bec5aee0728d67111d24)

## 英文一覧：全ての英文が掲載されてます
[![Image from Gyazo](https://i.gyazo.com/23ac6f368c278604ea56e3c11e30506b.png)](https://gyazo.com/23ac6f368c278604ea56e3c11e30506b)

## 検索機能：英文を検索できます。リセットで検索結果を戻せます。
[![Image from Gyazo](https://i.gyazo.com/e0d3fb5f4b675599095c7fd23327a59e.png)](https://gyazo.com/e0d3fb5f4b675599095c7fd23327a59e)

## 解説ページ：英文の解説ページです。
[![Image from Gyazo](https://i.gyazo.com/0e2ed166767f7e768b09cbdb49325097.png)](https://gyazo.com/0e2ed166767f7e768b09cbdb49325097)

**Comment by kenchasonakai** [comment]
LGTMです！
